const express=require('express');const path=require('path');const fs=require('fs');const crypto=require('crypto');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const helmet=require('helmet');const rateLimit=require('express-rate-limit');require('dotenv').config();
const app=express(),PORT=Number(process.env.PORT||3000),JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_BEFORE_DEPLOYMENT',DATA_FILE=path.join(__dirname,'data','database.json');
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'100kb'}));app.use(express.static(path.join(__dirname,'public')));
const loginLimiter=rateLimit({windowMs:15*60*1000,max:10,standardHeaders:true,legacyHeaders:false,message:{message:'Too many login attempts. Try again later.'}});app.use('/api/auth/login',loginLimiter);
function writeDB(db){fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2))}function ensureDB(){fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true});if(!fs.existsSync(DATA_FILE)){const username=process.env.ADMIN_USERNAME||'boopathi_183',password=process.env.ADMIN_PASSWORD||'DECEMBER2805';writeDB({admins:[{id:'admin-1',username,passwordHash:bcrypt.hashSync(password,12),displayName:'Boopathi'}],trips:[],activeTrip:null})}}function readDB(){ensureDB();return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}
function normalizeRate(value,fallback=20){const n=Number(value);if(Number.isFinite(n)&&n>0)return n;return Number.isFinite(fallback)&&fallback>0?fallback:20}
function waitingCharge(seconds){if(seconds<=3600)return 0;const extra=seconds-3600;return 50+Math.ceil(Math.max(0,extra-1)/1800)*25}
function liveTrip(t){if(!t)return null;const now=Date.now(),elapsed=Math.max(0,Math.floor((now-t.lastStateAt)/1000)),travel=t.travelSeconds+(t.waiting?0:elapsed),waiting=t.waitingSeconds+(t.waiting?elapsed:0),waitingCost=waitingCharge(waiting),travelCharge=(t.distanceMeters/1000)*t.rate;return {...t,originalFrom:t.originalFrom||t.route?.[0]||t.from,originalTo:t.originalTo||t.route?.[1]||t.to,travelSeconds:travel,waitingSeconds:waiting,distance:Math.floor(t.distanceMeters/1000),outboundDistance:Math.floor((t.outboundDistanceMeters||0)/1000),returnDistance:Math.floor((t.returnDistanceMeters||0)/1000),route:t.route||[t.from,t.to],travelCharge,waitingCharge:waitingCost,totalCost:travelCharge+waitingCost,currentCost:travelCharge+waitingCost}}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({message:'Authentication required.'});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({message:'Invalid or expired token.'})}}
function haversine(a,b,c,d){const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,z=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
ensureDB();
app.post('/api/auth/login',(req,res)=>{const {username,password}=req.body||{},db=readDB(),admin=db.admins.find(a=>a.username===username);if(!admin||!bcrypt.compareSync(String(password||''),admin.passwordHash))return res.status(401).json({message:'Invalid username or password.'});res.json({token:jwt.sign({sub:admin.id,username:admin.username},JWT_SECRET,{expiresIn:'8h'})})});
app.post('/api/trips/start',(req,res)=>{const {from,to,rate}=req.body||{},db=readDB();if(!from||!to)return res.status(400).json({message:'From and To are required.'});if(db.activeTrip)return res.status(409).json({message:'A trip is already active.'});const originalFrom=String(from).slice(0,200),originalTo=String(to).slice(0,200);db.activeTrip={id:crypto.randomUUID(),driverName:'Driver',from:originalFrom,to:originalTo,originalFrom,originalTo,rate:normalizeRate(rate,20),distanceMeters:0,outboundDistanceMeters:0,returnDistanceMeters:0,returnTrip:false,waiting:false,travelSeconds:0,waitingSeconds:0,lastStateAt:Date.now(),startedAt:new Date().toISOString(),lastLat:null,lastLon:null,lastAccuracy:null,lastGpsAt:null,route:[originalFrom,originalTo],returnCount:0};writeDB(db);res.json({trip:liveTrip(db.activeTrip)})});
app.get('/api/trips/active',(req,res)=>res.json({trip:liveTrip(readDB().activeTrip)}));
app.patch('/api/trips/state',(req,res)=>{const db=readDB(),t=db.activeTrip;if(!t)return res.status(404).json({message:'No active trip.'});const now=Date.now(),elapsed=Math.max(0,Math.floor((now-t.lastStateAt)/1000));if(t.waiting)t.waitingSeconds+=elapsed;else t.travelSeconds+=elapsed;t.waiting=Boolean(req.body?.waiting);t.lastStateAt=now;writeDB(db);res.json({trip:liveTrip(t)})});
app.post('/api/trips/location',(req,res)=>{const db=readDB(),t=db.activeTrip;if(!t)return res.status(404).json({message:'No active trip.'});if(t.waiting)return res.status(409).json({message:'Distance is paused during waiting.'});const lat=Number(req.body?.lat),lon=Number(req.body?.lon),accuracy=Number(req.body?.accuracy),speed=Number(req.body?.speed);if(!Number.isFinite(lat)||!Number.isFinite(lon)||!Number.isFinite(accuracy))return res.status(400).json({message:'Invalid GPS data.'});if(accuracy>60)return res.json({trip:liveTrip(t),ignored:true,reason:'low_accuracy'});const gpsAt=Number(req.body?.timestamp)||Date.now();if(t.lastGpsAt&&gpsAt<=t.lastGpsAt)return res.json({trip:liveTrip(t),ignored:true,reason:'old_sample'});if(t.lastLat!==null){const delta=haversine(t.lastLat,t.lastLon,lat,lon),dt=Math.max(0.5,(gpsAt-t.lastGpsAt)/1000),implied=delta/dt,noise=Math.max(8,Math.min(35,(t.lastAccuracy||accuracy)*0.45));if(delta>noise&&implied<=55){t.distanceMeters+=delta;if(t.returnTrip)t.returnDistanceMeters=(t.returnDistanceMeters||0)+delta;else t.outboundDistanceMeters=(t.outboundDistanceMeters||0)+delta}}t.lastLat=lat;t.lastLon=lon;t.lastAccuracy=accuracy;t.lastGpsAt=gpsAt;const now=Date.now();t.travelSeconds+=Math.max(0,Math.floor((now-t.lastStateAt)/1000));t.lastStateAt=now;writeDB(db);res.json({trip:liveTrip(t)})});
app.post('/api/trips/return',(req,res)=>{const db=readDB(),t=db.activeTrip;if(!t)return res.status(404).json({message:'No active trip.'});if(t.returnTrip)return res.status(409).json({message:'Return Trip is already active.'});const oldFrom=t.originalFrom||t.from,oldTo=t.originalTo||t.to,now=Date.now(),elapsed=Math.max(0,Math.floor((now-t.lastStateAt)/1000));if(t.waiting)t.waitingSeconds+=elapsed;else t.travelSeconds+=elapsed;t.waiting=false;t.lastStateAt=now;t.returnTrip=true;t.returnCount=1;t.originalFrom=oldFrom;t.originalTo=oldTo;t.from=oldTo;t.to=oldFrom;t.route=[oldFrom,oldTo,oldFrom];writeDB(db);res.json({trip:liveTrip(t)})});
app.post('/api/trips/preview',(req,res)=>{const db=readDB();if(!db.activeTrip)return res.status(404).json({message:'No active trip.'});res.json({trip:liveTrip(db.activeTrip)})});
app.post('/api/trips/end',(req,res)=>{const db=readDB(),t=db.activeTrip;if(!t)return res.status(404).json({message:'No active trip.'});const now=Date.now(),elapsed=Math.max(0,Math.floor((now-t.lastStateAt)/1000));if(t.waiting)t.waitingSeconds+=elapsed;else t.travelSeconds+=elapsed;t.rate=normalizeRate(req.body?.rate,t.rate);const distanceMeters=Math.max(0,Number(t.distanceMeters)||0),travelCharge=distanceMeters/1000*t.rate,waitingCost=waitingCharge(t.waitingSeconds),record={id:t.id,createdAt:new Date().toISOString(),from:t.originalFrom||t.from,to:t.originalTo||t.to,originalFrom:t.originalFrom||t.from,originalTo:t.originalTo||t.to,returnTrip:Boolean(t.returnTrip),distance:Math.floor(distanceMeters/1000),distanceMeters:Math.round(distanceMeters),outboundDistance:Math.floor((t.outboundDistanceMeters||0)/1000),outboundDistanceMeters:Math.round(t.outboundDistanceMeters||0),returnDistance:Math.floor((t.returnDistanceMeters||0)/1000),returnDistanceMeters:Math.round(t.returnDistanceMeters||0),waitingSeconds:t.waitingSeconds,travelSeconds:t.travelSeconds,rate:t.rate,route:t.route||[t.from,t.to],returnCount:t.returnCount||0,travelCharge:Math.round(travelCharge),waitingCharge:Math.round(waitingCost),calculatedCost:Math.round(travelCharge+waitingCost),totalCost:Math.round(travelCharge+waitingCost)};db.trips.unshift(record);db.activeTrip=null;writeDB(db);res.json({trip:record})});
app.post('/api/trips/end-payment',(req,res)=>{const db=readDB(),id=String(req.body?.id||''),t=db.trips.find(x=>x.id===id);if(!t)return res.status(404).json({message:'Completed trip not found.'});const base=Number(t.calculatedCost??t.totalCost)||0,paidLess=Math.max(0,Number(req.body?.paidLess)||0);t.paidLess=Math.round(paidLess);t.totalCost=Math.max(0,Math.round(base-paidLess));writeDB(db);res.json({trip:t})});
app.get('/api/trips',(req,res)=>{const db=readDB(),q=String(req.query.search||'').toLowerCase(),filter=String(req.query.filter||'month');let list=db.trips.filter(t=>!q||`${t.from} ${t.to}`.toLowerCase().includes(q));if(filter==='month'){const n=new Date();list=list.filter(t=>{const d=new Date(t.createdAt);return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()})}if(filter==='cost')list.sort((a,b)=>b.totalCost-a.totalCost);if(filter==='km')list.sort((a,b)=>b.distance-a.distance);res.json({trips:list})});
app.delete('/api/trips/:id',(req,res)=>{const db=readDB(),n=db.trips.length;db.trips=db.trips.filter(t=>t.id!==req.params.id);if(n===db.trips.length)return res.status(404).json({message:'Trip not found.'});writeDB(db);res.json({ok:true})});
app.get('/api/admin/dashboard',auth,(req,res)=>{const t=liveTrip(readDB().activeTrip),active=t?[t]:[];res.json({activeTrips:active,pendingPayments:active.reduce((s,x)=>s+x.currentCost,0),fleet:1})});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'DriveTrack API',time:new Date().toISOString()}));
app.get('{*splat}',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({message:'API route not found.'});let html=fs.readFileSync(path.join(__dirname,'public','index.html'),'utf8');const key=process.env.GOOGLE_MAPS_API_KEY||'';if(key)html=html.replace('<script src="js/app.js"></script>',`<script src="https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&callback=initDriveTrackMap" async defer></script><script src="js/app.js"></script>`);res.send(html)});
app.listen(PORT,'0.0.0.0',()=>console.log(`DriveTrack running on port ${PORT}`));
